### ISSUE TITLE
希望能加上wifi下自动/手动 离线 文章（流量农民伤不起）

### ISSUE THREAD

**Issue by F-TD5X** [nihgwu/NeoReader#5]

**Comment by nihgwu** [comment]
其实你不用担心流量的问题，牛读已经考虑的很多情况了，如果是在 wifi 情况下会做缓存的（图片除外）还有就是保持请求的流量尽量小，比如 api 或者手机版的 html 文件而不需其他 js 、css 文件
不过5分钟自动更新数据，之前的逻辑是 wif 的时候才会自动更新，后来觉得每次都要手动下来太麻烦了就去掉了，所以现在有网络超过五分钟就自动更新数据了，或许后面加一个开关吧
