### ISSUE TITLE
请问，Github的trending是自己爬取HTML页面再解析显示的吗

### ISSUE THREAD

**Issue by TellH** [nihgwu/NeoReader#6]

**Comment by nihgwu** [comment]
是的，说明里已经说的

**Comment by TellH** [comment]
thx

**Comment by nihgwu** [comment]
对了，其实不算爬的 HTML 吧，牛读基本都是秉持最小流量消耗的原则，所以 trending 其实是请求的项目首页的 API（官方提供），返回一个 编译成 HTML 的 README，但是不包含任何其他的 js、css 之类的文件

**Comment by TellH** [comment]
嗯，因为Github提供返回Json的API没有Trending，所以只能解析接收到的HTML文本了

**Comment by nihgwu** [comment]
不是这样的，其实 trending 我用了第三方的 api，详情页面是官方 api，github没有爬页面

**Comment by TellH** [comment]
咦，求API地址

**Comment by nihgwu** [comment]
公开分享貌似不太好
https://github.com/xiekw2010/react-native-gitfeed

**Comment by TellH** [comment]
非常感谢！

**Comment by ivanwonder** [comment]
@nihgwu 请问一下仓库的readme你是怎么处理的，我看readme的接口返回的数据是base64位加密，可以直接返回html或者markdown格式的字符串么

**Comment by nihgwu** [comment]
@ivanwonder https://developer.github.com/v3/media/#html-1
