### ISSUE TITLE
“本主题需要登录才能查看”应该怎么解决？

### ISSUE THREAD

**Issue by jizusun** [nihgwu/NeoReader#7]
V2EX上有些帖子是需要登录的，请问怎么办？

**Comment by nihgwu** [comment]
这个。。V2EX 是可以登录的啊，在 list 页面长按出快捷菜单，点最上面的那个头像登录，主要是交易板块的帖子需要登录，登录之后还可以回复的

**Comment by nihgwu** [comment]
后面我直接加登录按钮吧

**Comment by jizusun** [comment]
好隐蔽啊～
多谢提醒！

**Comment by nihgwu** [comment]
@smilingsun 是的呢，为了不影响主体设计风格，欢迎提建议哈😄
